run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: ccw
  govet:
    enable-all: true
  revive:
    rules:
      - name: exported
        disabled: true
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - revive
    - misspell
    - unconvert
    - unparam
  disable:
    - depguard # Can be enabled with custom rules if needed

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0