name: Swift CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: SwiftLint Auto Fix
        run: swiftlint autocorrect

      - name: Run SwiftLint
        run: swiftlint lint --strict --quiet --reporter github-actions-logging

  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: swiftpm-build-${{ runner.os }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            swiftpm-build-${{ runner.os }}-

      - name: Setup Swift 5.9
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.9

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build Debug
        run: swift build --configuration debug

      - name: Build Release
        run: swift build --configuration release

  test:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: swiftpm-test-${{ runner.os }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            swiftpm-test-${{ runner.os }}-

      - name: Setup Swift 
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.9

      - name: Resolve dependencies
        run: swift package resolve

      - name: Run tests
        run: swift test --enable-code-coverage