name: Swift CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-15
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache SwiftLint
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/swiftlint
          key: swiftlint-${{ runner.os }}

      - name: Install SwiftLint
        run: |
          if ! command -v swiftlint &> /dev/null; then
            brew install swiftlint
          fi

      - name: Run SwiftLint
        run: swiftlint lint --quiet --reporter github-actions-logging

  build:
    name: Build (${{ matrix.configuration }})
    runs-on: macos-15
    strategy:
      matrix:
        configuration: [debug, release]
      fail-fast: false  # Don't cancel other builds if one fails
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: swiftpm-${{ matrix.configuration }}-${{ runner.os }}-${{ hashFiles('Package.resolved', 'Package.swift') }}
          restore-keys: |
            swiftpm-${{ matrix.configuration }}-${{ runner.os }}-
            swiftpm-${{ runner.os }}-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build ${{ matrix.configuration }}
        run: swift build --configuration ${{ matrix.configuration }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}-build
          path: .build/${{ matrix.configuration }}/
          retention-days: ${{ matrix.configuration == 'release' && 7 || 1 }}

  test:
    name: Unit Tests
    runs-on: macos-15
    env:
      LLVM_PROFILE_FILE: .build/debug/default.profraw
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: swiftpm-debug-${{ runner.os }}-${{ hashFiles('Package.resolved', 'Package.swift') }}
          restore-keys: |
            swiftpm-debug-${{ runner.os }}-
            swiftpm-${{ runner.os }}-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Ensure LLVM profile directory exists
        run: mkdir -p .build/debug

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .build/debug/codecov/
          retention-days: 7