name: Swift CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        swift: [5.7, 5.8, 5.9]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: swiftpm-${{ runner.os }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            swiftpm-${{ runner.os }}-
              
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: SwiftLint Auto Fix
        run: swiftlint autocorrect

      - name: Run SwiftLint
        run: swiftlint lint --strict --quiet --reporter github-actions-logging

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build
        run: swift build --configuration release

      - name: Run tests
        run: swift test --enable-code-coverage